### ISSUE TITLE
Your wav2lip.pth MS sharepoint seems not set to public.

### ISSUE THREAD

**Issue by piwawa** [Snowad14/IAStreameur#4]
![屏幕截图 2023-12-02 132237](https://github.com/Snowad14/IAStreameur/assets/46926496/29d4aa3a-8604-48c9-912d-c72a9c9af311)

You should go to [this link ](https://iiitaphyd-my.sharepoint.com/personal/radrabha_m_research_iiit_ac_in/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fradrabha%5Fm%5Fresearch%5Fiiit%5Fac%5Fin%2FDocuments%2FWav2Lip%5FModels%2Fwav2lip%2Epth&parent=%2Fpersonal%2Fradrabha%5Fm%5Fresearch%5Fiiit%5Fac%5Fin%2FDocuments%2FWav2Lip%5FModels&ga=1) and change this share link to ANYONE.

**Comment by Snowad14** [comment]
This is not my link, but the one on wav2lip so it's up to the creator to change it
